components/Filtros/FiltroCompetencia.jsx, components/ProcedimentosPorCaps/ProcedimentosPorCaps.jsx, package-lock.json, package.json, pages/cuidado-compartilhado/aps-ambulatorio/index.js, pages/cuidado-compartilhado/cuidado-compartilhado.module.css, pages/cuidado-compartilhado/raps-hospitalar/index.js, requests/cuidado-compartilhado.js, yarn.lock
O PR a seguir implementa os cards da página de Raps e Atenção hospitalar de acordo com as mudanças propostas pela equipe de SM.
- Consumo do novo componente CardGridInternacoes;
- Atualização nos textos do subtítulo, descrição e tooltip;
- Atualização nos textos dos cards;
- Atualização de mês e ano na descrição do CardPeriodosInternacao, antes era estático, agora passa a ser dinâmico;
- Atualiza o filtro filtroPeriodosInternacoesRapsAltas  de MULTI para SINGLE;
O pedido é a revisão desse PR tendo em vista os requisitos propostos e as regras do projeto.
@tainnaps
=> Feat implementa tabelas raps atencao hospitalar

components/Graficos/CondicaoUsuarios.jsx, components/Graficos/Donut.jsx, components/Graficos/index.js, components/Tabelas/TabelaGraficoDonut.jsx, pages/caps/atendimentoindividuais/index.js, pages/caps/novosusuarios/index.js, pages/caps/perfildousuario/index.js, pages/caps/producao/index.js, pages/caps/taxadeabandono/index.js, utils/removerDadosZerados.js
- Criar componente para o gráfico de condição dos usuários e usá-lo nas páginas
- Criação do componente e uso nas páginas
- Criação da função de remoção de dados zerados e uso dela no gráfico e tabela donut
=> [Refatoração] Gráfico Condição de usuários

components/Graficos/Encaminhamentos.jsx, components/Graficos/HistoricoTemporal.jsx, components/Graficos/ProcedimentosPorTempoServico.jsx, components/Graficos/index.js, helpers/getEncaminhamentosChartOptions.js, helpers/graficoProcedimentosPorTempoServico.js, pages/caps/procedimentosporusuarios/index.js, pages/cuidado-compartilhado/aps-ambulatorio/index.js, pages/cuidado-compartilhado/aps-caps/index.js
- Criar componentes para os gráficos de encaminhamentos e procedimentos x tempo de serviço para separar e englobar a lógica de cada componente
- Criação de helpers do gráfico de procedimentos x tempo de serviço
- Mudança dos nomes de funções e variáveis de helpers do gráfico de encaminhamentos para português e remoção das options do gráfico desse arquivo
- Criação dos componentes `GraficoEncaminhamentos` e `GraficoProcedimentosPorTempoServico`, bem com uso deles em suas respectivas páginas
- Uso do componente `GraficoHistoricoTemporal` na página de procedimentos por usuários
- Remoção da legenda do `GraficoHistoricoTemporal`
=> [Refatoração] Gráficos de encaminhamentos e procedimentos

constants/FILTROS.js, pages/outros-raps/consultorio-na-rua/index.js, pages/outros-raps/reducao-de-danos/index.js
- Usar os componentes de gráficos nas páginas de _Consultório na rua_ e _Redução de danos_ do painel de **Outros serviços RAPS** para facilitar manutenção.
=> [Consultório na rua e Redução de danos] Usa componentes de gráficos

pages/outros-raps/ambulatorio/index.js, requests/outros-raps.js, utils/addQueryParamSeExiste.js
- Consumir os endpoints novos das páginas de ambulatório.
=> Altera endpoints de ambulatório

pages/outros-raps/reducao-de-danos/index.js, requests/outros-raps.js
- Usar novos endpoints de redução de danos com filtros e cache para melhorar desempenho da página
=> Novos endpoints redução de danos

pages/outros-raps/resumo/index.js
- Trocar a requisição do card de redução de danos  na página de Resumo <> Outros RAPS para usar o novo endpoint com filtros e cache
=> [Resumo <> Outros RAPS] Corrige requisição card de redução de danos

pages/caps/atendimentoindividuais/index.js, requests/caps.js, utils/addQueryParamSeExiste.js
Com a refatoração do endpoint `atendimentosindividuais/porcaps` para acomodar parâmetros de estabelecimentos, períodos, linha de perfil e linha de idade,  foi necessário atualizar o consumo desse endpoint na página de "Atendimentos individuais", a fim de melhorar a performance de carregamento da página. Nesse PR, é feito o consumo desse endpoint a partir da adição dos novos parâmetros opcionais nas funções de requisição, e remoção de funções de filtro nos componentes que passaram a ser desnecessárias.
- Separar o consumo do endpoint em duas requisições diferentes, uma para os cards e nome do último mês disponível e outra para o gráfico de histórico temporal;
- Durante o primeiro carregamento da página requisitar apenas os dados com o atributo `estabelecimentos: 'Todos'` na requisição …
=> [Refactor]Novo endpoint atendimentos individuais

components/CardsAmbulatorio/CardsAmbulatorioUltimoMes.jsx, components/CardsAmbulatorio/CardsAtendimentoPorOcupacaoUltimoMes.jsx, pages/outros-raps/ambulatorio/index.js
O texto da tooltip do gráfico de Total de Atendimentos na página Outros RAPS <> Ambulatório estava com um erro de digitação. O texto era 'números de maior número', onde deveria ser “maior número de finais de semana no mês”. Além disso, o título do primeiro card da página de Ambulatório também precisava ser ajustado de 'Ambulatório', para “Atendimentos no Ambulatório de Saúde Mental”.
- Corrigir a tooltip do gráfico de Total de Atendimentos.
- Corrigir o título do primeiro card da página de Ambulatório.
- Verifique se o título do primeiro card da página de Ambulatório possui o texto “Atendimentos no Ambulatório de Saúde Mental”.
- Verifique se o texto da tooltip do gráfico Total de Atendimentos da página de Ambulatório é:  'Indicador é calculado a partir da divisão do total de atendimentos …
=> [Outros RAPS] Corrige texto da tooltip do gráfico Total de Atendimentos e título do primeiro card Ambulatório

components/Graficos/ProcedimentosPorTempoServico.jsx, helpers/graficoProcedimentosPorTempoServico.js, pages/caps/procedimentosporusuarios/index.js
O gráfico de Procedimento por usuários x tempo do usuário no serviço, na página de CAPS <> Procedimentos por usuários estava com o eixo X (tempo) desordenado.
- Corrigir a ordenação para que seja do menor tempo para o maior, iniciando em 'Até 6 meses' e terminando em '5 anos ou mais'.
- Verifique se a ordenação está correta, ou seja, do menor tempo para o maior, iniciando em 'Até 6 meses' e terminando em '5 anos ou mais'.
- Verifique se permanece correta ao aplicar filtros de período ou estabelecimento.
Esse PR não faz mudanças de configuração da aplicação.
=> [CAPS] Corrige ordenação do gráfico de Procedimento por usuários x tempo do usuário no serviço

pages/outros-raps/reducao-de-danos/index.js
Correção do texto de tooltip dos cards "Ações de redução de danos realizadas".
Corrigir o texto de tooltip para "Total de procedimentos registrados por estabelecimentos do tipo CAPS como 'ação de redução de danos', segundo informado pelos profissionais de saúde por meio dos Boletins de Produção Ambulatorial consolidados (BPA-c)."
Verifique se o texto da tooltip dos cards "Ações de redução de danos realizadas" da página Redução de danos <> Outros RAPS corresponde a Total de procedimentos registrados por estabelecimentos do tipo CAPS como 'ação de redução de danos', segundo informado pelos profissionais de saúde por meio dos Boletins de Produção Ambulatorial consolidados (BPA-c).".
Esse PR não faz mudanças de configuração da aplicação
=> [Outros RAPS] Fix: Corrige texto de tooltip dos cards "Ações de redução de danos realizadas"

pages/cuidado-compartilhado/aps-caps/index.js
Com o recém interesse de Curitiba em voltar a utilizar o painel de Saúde Mental, fiz uma breve revisão do painel desse município a fim de identificar possíveis problemas de software ou dados. Nessa revisão, foi descoberto um erro de digitação no texto de descrição dos cards da página Cuidado compartilhado <> APS e CAPS. O texto era "Quantidade de atendimentos de Saúde Mental realizados pela APS que resultarem em Encaminhamentos para CAPS.", quando deveria ser "Quantidade de atendimentos de Saúde Mental realizados pela APS que resultaram em Encaminhamentos para CAPS.".
- Corrigir o texto de descrição dos cards na página Cuidado compartilhado <> APS e CAPS.
=> [Cuidado compartilhado] Correção: Texto de descrição dos cards na página APS e CAPS

components/Graficos/BarrasProducao.jsx, components/Graficos/CondicaoUsuarios.jsx, components/Graficos/Encaminhamentos.jsx, components/Graficos/GeneroPorFaixaEtaria.jsx, components/Graficos/GraficoAtendimentos.jsx, components/Graficos/HistoricoTemporal.jsx, components/Graficos/ProcedimentosPorTempoServico.jsx, components/Graficos/RacaECor.jsx, pages/caps/perfildousuario/index.js, pages/caps/procedimentosporusuarios/index.js, pages/caps/producao/index.js, pages/cuidado-compartilhado/aps-ambulatorio/index.js, pages/outros-raps/ambulatorio/index.js, utils/gerarGraficoSemDados.js
Esse PR visa realizar a melhoria sugerida nesse [card](https://www.notion.so/impulsogov/Gr-ficos-zerados-em-munic-pios-que-n-o-tem-dado-informado-6b2331b6fda647ee97222bb2c49c1440) do board de bugs e melhorias. 
O objetivo principal é realizar a verificação dos dados e renderizar uma mensagem explicativa nos casos em que os municípios não possuem dados suficientes para criação dos gráficos.
- Verificar a existência de dados para criação dos gráficos no componente do gráfico;
- Implementar um gráfico específico contendo a mensagem 'Não temos dados (ou eles são insuficientes) nas competências existentes na Plataforma para criação desse gráfico.' para ser renderizado no lugar do gráfico original quando não houverem dados suficientes para criação dos gráficos;
Como esse PR se aplica a todos os …
=> [PAINEL] Melhoria: Gráficos zerados em municipios sem dados

components/Graficos/GeneroPorFaixaEtaria.jsx, helpers/graficoGeneroEFaixaEtaria.js
Uma das últimas mudanças de dados no painel de SM foi a quebra das faixas etárias do nível infantil nas tabelas que populam os gráficos de gênero e faixa etária. Com essa mudança, os gráficos de gênero e faixa etária não poderão continuar sendo ordenados por ordem alfabética.
Corrigir a ordenação do gráfico de gênero e faixa etária para comportar as mudanças nos intervalos de faixa etária.
Verifique na página CAPS <> Atendimentos individuais (O gráfico dessa página consome a tabela mais atualizada, já com essas mudanças) se a ordenação das faixas etárias está correta, ou seja, da menor idade para maior idade. Iniciando de '0 a 4 anos' e terminando em '60 anos ou mais'.
Esse PR não faz mudanças de configuração da aplicação.
=> [Painel] Ordena dados do gráfico de gênero e faixa etária

pages/index.js
É necessária a inclusão das logos dos novos municípios parceiros do painel.
Atualização dos logos dos municípios parceiros do painel.
Verifique se no fim da página inicial, na seção "Governos parceiros" estão as logos dos novos municípios.
O PR não faz mudanças de configuração.
=> [Home] Adiciona logo de novos munis parceiros

components/Graficos/GeneroPorFaixaEtaria.jsx
Uma das últimas mudanças de dados no painel de SM foi a quebra das faixas etárias do nível infantil nas tabelas que populam os gráficos de gênero e faixa etária. Com essa mudança, algumas categorias de faixa etária presentes no eixo X passaram a ficar ilegíveis em resoluções comuns.
Ajustar o estilo dos gráficos de gênero e faixa etária para que as categorias de faixa etária permaneçam legíveis em resoluções comuns.
Esse PR não faz mudanças de configuração.
=> [PAINEL] Ajuste de estilo nos gráficos de gênero e faixa etária

pages/outros-raps/ambulatorio/index.js
Corrigir os valores passados para a prop Dados no gráfico Total de Atendimentos na página Outros RAPS <> Ambulatório
=> [Ambulatório] HOTFIX: Corrige prop gráfico total de Atendimentos

constants/MUNICIPIOS_SEM_OUTROS_SERVICOS.js
Adicionar o município de Pacatuba na lista de munis sem consultório na rua.
Esse PR não faz mudanças de configuração.
=> [Outros RAPS] Adiciona Pacatuba na lista de municípios sem Consultório na Rua

pages/index.js
É necessária a inclusão das logos dos novos municípios parceiros e apoiadores do painel.
Atualização dos logos dos municípios parceiros e apoiadores do painel.
Verifique se no fim da página inicial, na seção "Governos parceiros" estão as logos dos novos municípios(Curitiba e Lagarto).
Verifique se no fim da página inicial, na seção "Apoio" estão as logos dos nossos apoiadores(IDIS e BNDES).
O PR não faz mudanças de configuração.
=> [Home]Adiciona novas logos de munis parceiros e de apoio

.github/pull_request_template.md
Este Pull Request faz parte dos esforços contínuos da equipe de engenharia da Impulso para aumentar a revisão dos Pull Requests(PRs) abertos. Após uma discussão interna, decidimos adotar uma versão mais enxuta do modelo de template inicialmente criado por @tainnaps, conforme detalhado neste [PR.](https://github.com/ImpulsoGov/SaudeMental/pull/89)
As modificações na estrutura do template de PR têm como objetivo simplificá-lo, reduzindo-o para apenas 3 seções:
- Descrição
- Objetivos
- Checklist de Validação
Além disso, a seção "Como Validar" será incorporada ao escopo do checklist de validação, caso seja necessário. O campo "Mudanças de configuração" será removido.
=> [DOCS] Atualiza template de Pull Request 

package.json, pages/_app.js
Esse PR se propõe a implementar a tarefa descrita nesse [card ](https://www.notion.so/impulsogov/Incluir-atributos-de-usu-rio-no-c-digo-do-site-pro-Hotjar-4d4c002a106041ff978262874157226a)
Adição da API de identificação do Hotjar no painel de Saúde Mental para incluir atributos de usuário nas gravações.
=> Enhacement: Adiciona identificador do hotjar nas páginas do painel

package.json, pages/_app.js
=> [Login] Correção: Novos usuários sem acesso

constants/MUNICIPIOS_SEM_OUTROS_SERVICOS.js
Adicionar Princesa Isabel - PB na lista de munis sem ambulatório e sem consultório na rua.
Adicionar Serra Talhada - PE na lista de munis com ambulatório mas que não conseguimos mostrar.
Verifique se o código de Princesa Isabel (251230) está presente na lista de munis:
=> [Outros RAPS] Adiciona novos munis sem ambulatório ou CnR

constants/MUNICIPIOS_SEM_OUTROS_SERVICOS.js
=> [OUTROS RAPS] Correção vírgula munis

next.config.js
=> [PAINEL] Corrige nome da org no sentry-config

constants/MUNICIPIOS_SEM_OUTROS_SERVICOS.js
Adicionar Serra Talhada na lista de municípios sem Consultório na Rua.
=> [Outros RAPS] Adiciona Serra Talhada na lista de municípios sem CnR

constants/API_URL.js
Com a recente mudança nas regras de negócio no modelo de login da API de usuários que é compartilhada entre o SM e o IP.
Fez-se necessário a mudança de URL para que as mudanças propostas lá não afetassem os usuários de SM, portanto esse PR se destina a mudar a URL para que essa aponte para a API de SM que contém o código da versão mais antiga da API de usuários.
=> [PAINEL] Mudança na URL da API de usuários

constants/API_URL.js
Esse PR se destina a atualizar a URL da API de usuários de saúde mental. Com as recentes mudanças no modelo de login do IP, fez-se necessário a separação das APIs de usuários.
=> [PAINEL] Adiciona URL nova da API de usuários
